name: first

on: [push]

jobs:
  job1:
    First Job
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Step 2
      run: env | sort

  job2:
    Second Job
    runs-on: windows-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Step 2
      run: "Get-ChildItem Env: | Sort-Object Name"
